# -*- coding: utf-8 -*-
{
    'name': 'eltarek Delivery Requests Generic aa',
    'version': '1.0',
    'category': 'Stock',
    'author':'Centione',
    'website': 'https://www.centione.com',
    'depends': ['purchase', 'hr', 'stock', 'analytic', 'account'],
    'data': [
        'security/ir_rule.xml',
        'security/ir.model.access.csv',
        'views/account_account_inherit.xml',
        'wizard/centione_process_request_views.xml',
        'wizard/products_category_approval_wizard.xml',
        'wizard/create_po.xml',
        'wizard/transfer_all.xml',
        'wizard/purchase_all.xml',
        'wizard/receive_all.xml',
        'wizard/cancel_wizard.xml',
        'wizard/lines_stock_wizard.xml',
        'views/product_category_view.xml',
        'views/centione_delivery_request_views.xml',
        'views/centione_purchase_request_views.xml',
        'views/centione_delivery_request_menus.xml',
        'views/centione_purchase_request_line.xml',
        'views/delivery_request_settings.xml',
        'data/centione_delivery_request_data.xml',
        'data/centione_delivery_request_sequence.xml',
        'data/mail_templates.xml',
        'data/centione_purchase_request_sequence.xml',
        'views/analytic_account_form.xml',
        'views/stock_picking.xml',
        'views/product_template_view.xml',
    ]
}
